# Generated by Django 4.1.2 on 2022-10-07 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0002_alter_thing_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="description",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(120)]
            ),
        ),
        migrations.AlterField(
            model_name="thing",
            name="quantity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
